export interface Order {
  OrderId: number
  Count: number
  UserId: number
  RechargeId: number
  AddTime: string
  OrderNumber: string
  State: number
  FromId: number
  DualAdmin: string
  ReturnInfo: string
  DualTime: {
    Time: string
    Valid: boolean
  }
  SuccessTime: {
    Time: string
    Valid: boolean
  }
  WarrantyDay: number
  AllMoney: number
  UnitMoney: number
  MainId: number
  VipId: number
  Account: string
  AccountName: string
  BuyUserNo: number
  GoodUserId: number
  GoodUserNo: number
  GoodMessage: string
  GoodType: number
  GoodStockPrice: number
  BackMoney: number
  GoodFaceValue: number
  RateValue: number
  BuyUserName: string
  GoodNo: number
  GoodId: number
  AllCount: number
  OrderTime: string
  OrderAllMoney: number
  Months: string
  PlatUrl: string
  ApiOrderId: number
  ApiOrderNumber: string
  Multiply: number
  PayId: number
  PayNumber: string
  PayMoney: number
  PayFee: number
  PayType: number
  PayRefundMoney: number
  PayRefundFee: number
  IsTuiDan: number
  IsTuiKuan: number
  BuyUrl: string
  ApiId: number
  GoodDetail: string
  ApiMsg: string
  NotifyUrl: string
  OuterNumber: string
  DeliverCount: number
  BuyMethod: number
  Sku: string
  FixedId: number
  FixedSku: string
  WorkCount: number
  TicalStatus: number
  TicalDay: number
  TicalDetail: string
  TicalPath: string
  ExpressId: number
  Remark: string
  ShopType: string
  ShopId: string
  ChaType: number
  ProType: number
  ChaPartner: string
  LinkStatus: number
  NotifyCardsStatus: number
  AfterNumber: string
  HasRefund: number
  CouponId: number
  CouponMoney: number
  CardId: number
  CardNo: string
  CardPwd: string
  CardApiId: number
  ApiCardId: string
  CardRemark: string
  CardStatus: number
  CardErrMsg: string
  IsAddExtension: boolean
  AutoRefundCard: number
  Ticheng: number
  Inmoney: number
  Profit: number
  EditApiOrder: number
  Rechinfo: any
  ApiName: string
  ApiCardStatus: number
  ApiCardType: number
  AccountMimeType: number
  TranNo: string
  TicalUrl: string
  TicalTime: string
  IsAddNumber: boolean
  IsWarrantyDay: boolean
  AccountForCopy: string
}

export interface OrderStatistics {
  goodName: string
  orderCount: number
  orderStates: { [key: number]: number }
  totalRefundCount: number
  totalRefundAmount: number
  totalSales: number
  totalCost: number
  totalProfit: number
  totalPlatformFee: number
  avgProfit: number
  profitMargin: number
  avgUnitPrice: number
  expectedProfit?: number
  calculatedPlatformFee?: number
}

export interface ApiResponse {
  orderList: Order[]
}
